arch:
  input_model_dim: 3
  output_model_dim: 2
  params:
    dropout: 0
  type: CNN3D_IA
  user_defined: true
best_run_path: ''
data:
  climatology_clipping: true
  climatology_mean_root: AIDE/databases/Russia/data_py/climatology_mean
  climatology_std_root: AIDE/databases/Russia/data_py/climatology_std
  data_dim: 3
  data_file: ESDC_RUSSIA.nc
  features:
  - surface_moisture
  - air_temperature_2m
  - evaporation
  features_selected:
  - 0
  - 1
  - 2
  input_size_test: (64,128,16)
  input_size_train: (32,32,16)
  input_size_val: (32,64,16)
  labels_file: GDIS_RUSSIA.nc
  lat_slice_test: 62, 46
  lat_slice_train: 62, 46
  lat_slice_val: 62, 54
  lon_slice_test: 24.3, 56.3
  lon_slice_train: 24.3, 56.3
  lon_slice_val: 24.3, 40.3
  n_samples: 1000
  name: DROUGHT
  nexp: '1'
  num_targets: 1
  root: /data/users/xaida/AIDE_private/AIDE/AIDE/databases/Russia/
  seed_idx: 1
  target_feature: ndvi
  test_slice:
    exp1:
    - '''20-April-2012'',''31-October-2012'''
  time_slice: '''January-2003'',''December-2018'''
  train_slice:
    exp1:
    - '''20-April-2010'',''31-October-2010'''
  val_slice:
    exp1:
    - '''20-April-2010'',''31-October-2010'''
debug: false
evaluation:
  metrics:
    MeanSquaredError: {}
    PearsonCorrCoef: {}
    SpearmanCorrCoef: {}
  visualization:
    activate: true
    params:
      gt_color_map: RdBu
      output_color_map: RdBu
      time_aggregation: false
      vmax: 1
      vmin: -1
  xai:
    activate: false
    params:
      params: null
      type: Saliency
experiment_id: 2024-01-17_23-02-59
from_scratch: true
implementation:
  data_loader:
    num_workers: 16
    sampler: None
  loss:
    activation:
      type: linear
    masked: true
    package: torch.nn
    params:
      delta: 1.5
      reduction: none
    type: HuberLoss
    user_defined: false
  optimizer:
    gclip_value: 0
    lr: 5.0e-05
    type: Adam
    weight_decay: 0
  trainer:
    accelerator: cpu
    batch_size: 2
    devices: 1
    early_stop: 10
    epochs: 1000
    monitor:
      metric: loss
      split: val
    monitor_mode: min
    save_dir: experiments/
name: AIDE
save_path: AIDE/experiments/experiment_2_CNN3D_IA_bs_2_n_1000/2024-01-17_23-02-59
task: ImpactAssessment
