arch:
  input_model_dim: 3
  output_model_dim: 3
  params:
    batch_first: true
    bias: true
    final_conv: true
    hidden_dim: 32
    input_dim: 3
    kernel_size: (3,3)
    num_layers: 3
    output_dim: 1
    return_all_layers: false
  type: ConvLSTM
  user_defined: true
best_run_path: ''
data:
  climatology_clipping: false
  climatology_mean_root: './databases/Russia/data_py/climatology_mean'
  climatology_std_root: './databases/Russia/data_py/climatology_std'
  data_dim: 3
  data_file: 'ESDC_RUSSIA.nc'
  features:
  - surface_moisture
  - air_temperature_2m
  - evaporation
  features_selected:
  - 0
  - 1
  - 2
  input_size_test: (48,80,32)
  input_size_train: (48,80,32)
  input_size_val: (48,80,32)
  labels_file: 'GDIS_RUSSIA.nc'
  lat_slice_test: 63, 51
  lat_slice_train: 51, 39
  lat_slice_val: 63, 51
  lon_slice_test: 47.3, 67.3
  lon_slice_train: 27.3, 67.3
  lon_slice_val: 27.3, 47.3
  name: DROUGHT
  nexp: '1'
  num_classes: 2
  root: './databases/Russia/'
  seed_idx: 1
  test_slice:
    exp1:
    - '''1-January-2010'',''31-December-2010'''
  time_slice: '''January-2003'',''December-2018'''
  train_slice:
    exp1:
    - '''1-January-2003'',''31-December-2010'''
  val_slice:
    exp1:
    - '''1-January-2003'',''31-December-2010'''
debug: false
evaluation:
  characterization:
    activate: false
    params:
      min_area_holes: 64
      min_area_objects: 64
      min_distance: 100
      remove_scant: false
      threshold:
        F1Score:
          task: binary
      threshold_lower_is_best: false
      time_aggregation: true
  metrics:
    AUROC:
      task: binary
    Accuracy:
      task: binary
    AveragePrecision:
      task: binary
    F1Score:
      task: binary
  visualization:
    activate: true
    params:
      time_aggregation: true
  xai:
    activate: false
    params:
      mask: events
      min_area_holes: 64
      min_area_objects: 64
      min_distance: 100
      out_agg_dim:
      - 2
      - 3
      params: null
      remove_scant: false
      threshold:
        F1Score:
          num_classes: 4
          task: multiclass
      threshold_lower_is_best: false
      time_aggregation: true
      type: IntegratedGradients
experiment_id: 2024-02-05_20-33-44
from_scratch: true
implementation:
  data_loader:
    num_workers: 12
  loss:
    activation:
      type: linear
    masked: true
    package: torchvision.ops
    params:
      alpha: 0.92
      gamma: 1.0
      reduction: none
    type: sigmoid_focal_loss
    user_defined: false
  optimizer:
    gclip_value: 0
    lr: 0.0001
    type: Adam
    weight_decay: 0
  trainer:
    accelerator: gpu
    batch_size: 1
    devices: 1
    early_stop: 10
    epochs: 500
    monitor:
      metric: F1Score
      split: val
    monitor_mode: max
name: AIDE
save_path: experiments/2024-02-05_20-33-44
task: Classification
